[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "starlette-admin-geospatial"
description = "A starlette-admin plugin"
readme = "README.md"
license = "MIT"
requires-python = ">=3.11"
authors = [{ name = "Jocelin Hounon", email = "hounonj@gmail.com" }]
version = "0.1.0"

classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Typing :: Typed",
]

dependencies = ["starlette-admin[i18n]>=0.16,<1.0"]

[project.urls]
Homepage = "https://github.com/jowilf/starlette-admin-geospatial"
Repository = "https://github.com/jowilf/starlette-admin-geospatial"

[project.entry-points."starlette_admin.plugins"]
geospatial = "starlette_admin_geospatial:GeospatialPlugin"

[tool.hatch.build.targets.wheel]
packages = ["src/starlette_admin_geospatial"]


[tool.uv.sources]
starlette-admin = { path = "../../", editable = true }

[dependency-groups]
dev = [
    "uvicorn[standard]>=0.51.0",
    "pytest>=8.0",
    "pytest-asyncio>=0.24",
    "httpx>=0.27",
    "sqlalchemy>=2.0",
    "uvicorn[standard]>=0.30",
]
