[project]
site_name = "Starlette Admin"
site_description = "Fast, beautiful and extensible administrative interface framework for Starlette/FastApi applications"
site_url = "https://jowilf.github.io/starlette-admin"
repo_name = "jowilf/starlette-admin"
repo_url = "https://github.com/jowilf/starlette-admin"
edit_uri = "https://github.com/jowilf/starlette-admin/tree/main/docs"
docs_dir = "docs"
watch = ["starlette_admin"]
extra_css = ["stylesheets/extra.css"]

nav = [
  { "Overview" = "index.md" },
  { "Tutorials" = [
    { "Introduction" = "tutorials/index.md" },
    { "Building your first admin panel" = "tutorials/basic/index.md" },
  ] },
  { "User Guide" = [
    { "Getting Started" = "user-guide/getting-started/index.md" },
    { "Configurations" = [
      { "Admin" = "user-guide/configurations/admin/index.md" },
      { "ModelView" = "user-guide/configurations/modelview/index.md" },
    ] },
    { "Forms Validations" = "user-guide/validations/index.md" },
    { "Authentication" = "user-guide/authentication/index.md" },
    { "Managing Files" = "user-guide/files/index.md" },
    { "Actions" = "user-guide/actions/index.md" },
    { "Multiple Admin" = "user-guide/multiple-admin/index.md" },
  ] },
  { "Advanced User Guide" = [
    { "Custom Field" = "advanced/custom-field/index.md" },
    { "Extending BaseModelView" = "advanced/base-model-view/index.md" },
  ] },
  { "Deployment" = "deployment/index.md" },
  { "Alternatives, Inspiration and Comparisons" = "alternatives/index.md" },
  { "API Reference" = [
    { "Contrib" = [
      { "SQLAlchemy" = [
        { "ModelView" = "api/contrib/sqlalchemy/modelview/index.md" },
      ] },
    ] },
    { "Fields" = "api/fields/index.md" },
    { "Views" = "api/views/index.md" },
    { "BaseAdmin" = "api/base-admin/index.md" },
    { "Auth" = "api/auth/index.md" },
    { "Actions" = "api/actions/index.md" },
  ] },
  { "Changelog" = "changelog/index.md" },
]

[project.theme]
favicon = "assets/favicon.ico"
features = [
  "content.code.copy",
  "content.action.view",
  "search.suggest",
  "search.highlight",
  "navigation.tabs",
  "navigation.footer",
  "content.tabs.link",
]


[project.theme.icon]
logo = "material/database-settings"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "custom"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
primary = "custom"

[project.markdown_extensions.admonition]

[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true

[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.attr_list]

[project.plugins.search]

[project.plugins.mkdocstrings.handlers.python.options]
show_root_heading = true
show_source = true

[project.extra.analytics]
provider = "google"
property = "G-PRC6TQ4K82"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/jowilf"

[[project.extra.social]]
icon = "fontawesome/brands/twitter"
link = "https://twitter.com/jowilf"

[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/in/jocelin-hounon-2008aa139"
