[project]
name = "09-actions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "sqlalchemy>=2.0.50",
    "starlette-admin",
    "uvicorn[standard]>=0.39.0",
]

[tool.uv.sources]
starlette-admin = { workspace = true, editable = true }
