[project]
name = "07-hr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faker>=40.23.0",
    "markdown>=3.10.2",
    "pillow>=10.0.0",
    "sqlalchemy>=2.0.50",
    "starlette-admin",
    "uvicorn[standard]>=0.39.0",
]

[tool.uv.sources]
starlette-admin = { workspace = true, editable = true }
