[project]
name = "14-sqlmodel"
version = "0.1.0"
description = "Comprehensive SQLModel example for starlette-admin"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic[email]>=2.0",
    "sqlmodel>=0.0.18",
    "starlette-admin[excel]",
    "uvicorn[standard]>=0.29.0",
]

[tool.uv.sources]
starlette-admin = { workspace = true, editable = true }
